export const MONSTER_LIST_REQUEST = 'MONSTER_LIST_REQUEST';
export const MONSTER_LIST_SUCCESS = 'MONSTER_LIST_SUCCESS';
export const MONSTER_LIST_FAIL = 'MONSTER_LIST_FAIL';

export const GET_NEXT_MONSTER_PAGE_REQUEST = 'GET_NEXT_MONSTER_PAGE_REQUEST';
export const GET_NEXT_MONSTER_PAGE_SUCCESS = 'GET_NEXT_MONSTER_PAGE_SUCCESS';
export const TOGGLE_MONSTER_FAVORITE = 'TOGGLE_MONSTER_FAVORITE';

export const SHOW_FAVORITE_MONSTERS = 'SHOW_FAVORITE_MONSTERS';
